/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SDHC1.h
**     Project     : HelloTeensy35
**     Processor   : MK64FX512VLQ12
**     Component   : SDHC_LDD
**     Version     : Component 00.001, Driver 01.04, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-10-04, 12:03, # CodeGen: 17
**     Abstract    :
**          This component implements a SD host controller driver 
**          interface. Handles control and data transfers to/from
**          SD and MMC cards.
**     Settings    :
**          Component name                                 : SDHC1
**          Device                                         : SDHC
**          Settings                                       : 
**            Interface                                    : 1-bit data mode
**            Bus clock                                    : 400 kHz
**            Data timeout exponent                        : 20
**            DMA                                          : 
**              Read watermark                             : 16
**              Write watermark                            : 16
**            Buffers                                      : 
**              Transfer buffer table size                 : 8
**          Interrupt service/event                        : Enabled
**            SDHC                                         : INT_SDHC
**            SDHC priority                                : medium priority
**          Pins                                           : 1-bit data mode
**            CLK pin                                      : ADC0_DP2/ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2
**            CMD pin                                      : ADC0_DM2/ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT
**            Data                                         : 
**              DAT0 pin                                   : ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN
**              DAT1                                       : Disabled
**              DAT2                                       : Disabled
**              DAT3                                       : Disabled
**          Initialization                                 : 
**            Enable device                                : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnCardInserted                             : Enabled
**              OnCardRemoved                              : Enabled
**              OnFinished                                 : Enabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init           - LDD_TDeviceData* SDHC1_Init(LDD_TUserData *UserDataPtr);
**         DetectCards    - LDD_TError SDHC1_DetectCards(LDD_TDeviceData *DeviceDataPtr);
**         SelectCard     - LDD_TError SDHC1_SelectCard(LDD_TDeviceData *DeviceDataPtr, uint8_t Id);
**         GetCardInfo    - LDD_TError SDHC1_GetCardInfo(LDD_TDeviceData *DeviceDataPtr,...
**         TransferBlocks - LDD_TError SDHC1_TransferBlocks(LDD_TDeviceData *DeviceDataPtr,...
**         GetStatus      - LDD_SDHC_TStatus SDHC1_GetStatus(LDD_TDeviceData *DeviceDataPtr);
**         GetError       - LDD_SDHC_TError SDHC1_GetError(LDD_TDeviceData *DeviceDataPtr, uint32_t...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SDHC1.h
** @version 01.04
** @brief
**          This component implements a SD host controller driver 
**          interface. Handles control and data transfers to/from
**          SD and MMC cards.
*/         
/*!
**  @addtogroup SDHC1_module SDHC1 module documentation
**  @{
*/         

#ifndef __SDHC1_H
#define __SDHC1_H

/* MODULE SDHC1 */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define SDHC1_PRPH_BASE_ADDRESS  0x400B1000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define SDHC1_Init_METHOD_ENABLED      /*!< Init method of the component SDHC1 is enabled (generated) */
#define SDHC1_DetectCards_METHOD_ENABLED /*!< DetectCards method of the component SDHC1 is enabled (generated) */
#define SDHC1_SelectCard_METHOD_ENABLED /*!< SelectCard method of the component SDHC1 is enabled (generated) */
#define SDHC1_GetCardInfo_METHOD_ENABLED /*!< GetCardInfo method of the component SDHC1 is enabled (generated) */
#define SDHC1_TransferBlocks_METHOD_ENABLED /*!< TransferBlocks method of the component SDHC1 is enabled (generated) */
#define SDHC1_GetStatus_METHOD_ENABLED /*!< GetStatus method of the component SDHC1 is enabled (generated) */
#define SDHC1_GetError_METHOD_ENABLED  /*!< GetError method of the component SDHC1 is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define SDHC1_OnCardInserted_EVENT_ENABLED /*!< OnCardInserted event of the component SDHC1 is enabled (generated) */
#define SDHC1_OnCardRemoved_EVENT_ENABLED /*!< OnCardRemoved event of the component SDHC1 is enabled (generated) */
#define SDHC1_OnFinished_EVENT_ENABLED /*!< OnFinished event of the component SDHC1 is enabled (generated) */


#define SDHC1_NO_CARD 1                /* Special card ID for the SelectCard method indicating that no card should be selected (unselect all). */

typedef enum {
  SDHC1_BUS_CLOCK_STATIC
} SDHC1_TBusClock;

/*
** ===================================================================
**     Method      :  SDHC1_Init (component SDHC_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property <"Enable device"> is set to "yes" then the device
**         is also enabled (see the description of the <Enable> method).
**         In this case the <Enable> method is not necessary and need
**         not to be generated. This method can be called only once.
**         Before the second call of Init the <Deinit> method must be
**         called first.
**     @param
**         UserDataPtr     - Pointer to user data
**                           structure pointer.
**     @return
**                         - Pointer to the device data structure. 
*/
/* ===================================================================*/
LDD_TDeviceData* SDHC1_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  SDHC1_DetectCards (component SDHC_LDD)
*/
/*!
**     @brief
**         Detects newly inserted and removed cards. The OnCardInserted
**         event will be called for every new card and the
**         OnCardRemoved event will be called for every removed card.
**         This method should be used when card detection pin is not
**         available.
**     @param
**         DeviceDataPtr   - Pointer to the device
**                           data structure.
**     @return
**                         - 
**                           Error code, possible values:
**                           ERR_OK - Card detection started
**                           ERR_DISABLED - The component is disabled
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_BUSY - Another card operation is in
**                           progress
*/
/* ===================================================================*/
LDD_TError SDHC1_DetectCards(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  SDHC1_SelectCard (component SDHC_LDD)
*/
/*!
**     @brief
**         Selects a card by its identification number. All further
**         operations will apply to this card. Special card
**         identification number <compId>_NO_CARD will deselect the
**         active card.
**     @param
**         DeviceDataPtr   - Pointer to the device
**                           data structure.
**     @param
**         Id              - Card identification number passed by the
**                           OnCardInserted event parameter.
**     @return
**                         - 
**                           Error code, possible values:
**                           ERR_OK - Card selection started
**                           ERR_DISABLED - The component is disabled
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_BUSY - Another card operation is in
**                           progress
**                           ERR_PARAM_ID - Invalid card ID
*/
/* ===================================================================*/
LDD_TError SDHC1_SelectCard(LDD_TDeviceData *DeviceDataPtr, uint8_t Id);

/*
** ===================================================================
**     Method      :  SDHC1_GetCardInfo (component SDHC_LDD)
*/
/*!
**     @brief
**         Returns card information about the selected card. Method
**         call starts the card information retrieval process. After
**         the card information has been received, the OnFinished event
**         is called (the component state changes to idle) and the
**         information is stored in the specified variable.
**     @param
**         DeviceDataPtr   - Pointer to the device
**                           data structure.
**     @param
**         InfoPtr         - Pointer to a variable, where card
**                           information will be stored.
**     @return
**                         - 
**                           Error code, possible values:
**                           ERR_OK - Card information retrieval started
**                           ERR_DISABLED - The component is disabled
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_BUSY - Another card operation is in
**                           progress
*/
/* ===================================================================*/
LDD_TError SDHC1_GetCardInfo(LDD_TDeviceData *DeviceDataPtr, LDD_SDHC_TCardInfo *InfoPtr);

/*
** ===================================================================
**     Method      :  SDHC1_TransferBlocks (component SDHC_LDD)
*/
/*!
**     @brief
**         Initiates a data block transfer on the selected card.
**         Transfer can be a read or write operation depending on the
**         transfer operation parameter. Read operation reads data
**         blocks from the specified address on a memory card and
**         stores their content into buffers specified by the buffer
**         descriptor list. Write operation writes data blocks
**         specified by the buffer descriptor list to a card memory on
**         the specified address. Data blocks should be the same size
**         and the block size should be supported by the memory card.
**         Buffer addresses should be aligned to a hardware specific
**         address boundary.
**     @param
**         DeviceDataPtr   - Pointer to the device
**                           data structure.
**     @param
**         Operation       - Transfer operation
**     @param
**         Address         - Card memory address. Byte address
**                           in case of standard capacity memory cards,
**                           512 byte block number in case of high
**                           capacity memory cards.
**     @param
**         BufferDescListPtr - Pointer to
**                           data block buffer descriptor list.
**     @param
**         BufferDescCount - Data block buffer
**                           descriptor list item count
**     @return
**                         - 
**                           Error code, possible values:
**                           ERR_OK - Transfer started
**                           ERR_DISABLED - The component is disabled
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_BUSY - Another card operation is in
**                           progress
**                           ERR_PARAM_ADDRESS - Invalid buffer address
**                           (one or more buffer address from the list
**                           of buffer descriptors is misaligned)
**                           ERR_PARAM_BUFFER_COUNT - Buffer count
**                           exceeds the internal buffer table size
*/
/* ===================================================================*/
LDD_TError SDHC1_TransferBlocks(LDD_TDeviceData *DeviceDataPtr, LDD_SDHC_TTransferOperation Operation, uint32_t Address, LDD_SDHC_TBufferDesc *BufferDescListPtr, uint16_t BufferDescCount);

/*
** ===================================================================
**     Method      :  SDHC1_GetStatus (component SDHC_LDD)
*/
/*!
**     @brief
**         Returns the current component status, specifying the ongoing
**         operation.
**     @param
**         DeviceDataPtr   - Pointer to the device
**                           data structure.
**     @return
**                         -  Component status.
*/
/* ===================================================================*/
LDD_SDHC_TStatus SDHC1_GetStatus(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  SDHC1_GetError (component SDHC_LDD)
*/
/*!
**     @brief
**         Returns the last error code and the memory address where the
**         error occurred (if applicable).
**     @param
**         DeviceDataPtr   - Pointer to the device
**                           data structure.
**     @param
**         AddressPtr      - Pointer to a variable, where
**                           the error address will be stored.
**     @return
**                         -  The last error code.
*/
/* ===================================================================*/
LDD_SDHC_TError SDHC1_GetError(LDD_TDeviceData *DeviceDataPtr, uint32_t *AddressPtr);

/*
** ===================================================================
**     Method      :  SDHC1_Interrupt (component SDHC_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(SDHC1_Interrupt);

/* END SDHC1 */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __SDHC1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
